### ISSUE TITLE
펀딩 상세페이지 기능 구현

### ISSUE THREAD

**Issue by HarrySeop** [Team-Fundy/Fundy-FE#12]
## Describe
펀딩 상세페이지 기능 구현 - 애니메이션, 펀딩보상 리스트 제외를 목표로 함

## 🍀 Tasks

- [ ] 컴포넌트로 분리하여 기초 레이아웃 다시 잡기
- [ ] 이미지 확대 컴포넌트 구현
- [ ] 펀딩 상세 메시지 창 구현
- [ ] 스크롤 시 다크모드로 전환
- [ ] (아래로 스크롤 후) 5개의 소개박스 컴포넌트 구현
- [ ] (아래로 스크롤 후) 사이드 카드 두개 구현
- [ ] 소개 박스를 클릭 시 모달 컴포넌트 구현
