### ISSUE TITLE
메인 홈 - 디자인 기준 해상도 100%로 변경

### ISSUE THREAD

**Issue by JuJangGwon** [Team-Fundy/Fundy-FE#5]
### Describe
메인 홈 - 디자인 기준 해상도 현재 70%에서 -> 100%로 변경 
### ✅ Tasks
- [x] 메인홈-헤더 해상도 변경 
- [x] 메인홈-타이틀배너 해상도 변경 
- [ ] 메인홈-개발노트리스트 해상도 변경
- [x] 메인홈-신규프로젝트리스트 해상도 변경
- [x] 메인홈-장르별프로젝트리스트 해상도 변경

23.11.19 -
헤더, 타이틀 배너, 신규프로젝트, 장르별 프로젝트 리스트 해상도 변경 완료
개발노트 리스트는 디자인 변경예정으로 미적용

**Comment by JuJangGwon** [comment]
- 23.11.19 -
헤더, 타이틀 배너, 신규프로젝트, 장르별 프로젝트 리스트 해상도 변경 완료 
개발노트 리스트는 디자인 변경예정으로 미적용
