### ISSUE TITLE
헤더 - 상단 헤더 UI, 디자인 변경

### ISSUE THREAD

**Issue by JuJangGwon** [Team-Fundy/Fundy-FE#7]
## task
- [ ] 기존 좌측 버튼 그룹 [장르 / 인기 / 신규 ] 에서 [펀딩 / 프로모션 / 펀디이야기 / 문의사항]으로 종류 변경
- [ ] 헤더 다크모드 구현
- [ ] 헤더 배경 투명 모드 구현
- [ ] 로고, 좌측 상단 text 버튼 아이콘으로 변경
