### ISSUE TITLE
프로젝트 업로드 페이지 구현

### ISSUE THREAD

**Issue by JuJangGwon** [Team-Fundy/Fundy-FE#9]
### Describe
프로젝트업로드 페이지 디자인 및 기능 구현 

### Task
- [ ] 프로젝트 유형 선택 페이지 만들기 
- [ ] 유의사항 안내 페이지 만들기 

##### 펀딩 업로드 페이지 만들기 
  - [ ] 사이드바 ( 프로젝트 업로드 진척도 시각적으로 보이는 ) 구현 
  - [ ] 크리에이터 정보작성 페이지 만들기 
  - [ ] 프로젝트 정보작성 페이지 만들기
  - [ ] 펀딩 일정 작성 페이지 만들기
  - [ ] 리워드 작성 페이지 만들기
  - [ ] 프로젝트 계획 작성 페이지 만들기
  - [ ] 개발 노트 설정 페이지 만들기
